### ISSUE TITLE
Can't run "npm install" at 64bit nodejs v6.11.3 for Mac 

### ISSUE THREAD

**Issue by yushiro** [reallyimeric/lp-store-calculator#6]
`➜ /Documents/Game/eve/lp-store-calculator git:(master)>npm install
module.js:471
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

**Comment by reallyimeric** [comment]
I don‘t have a Mac and I'm using travis-ci.org to confirm this.

I can install dependencies successfully on node v8.5.0 linux.

This may be an issue with your network connection to npm registry, and you can try using a proxy, using some other npm registry (e.g. [Taobao's](https://npm.taobao.org/)) or just try some times again.

**Comment by reallyimeric** [comment]
Travis-ci.org can install dependencies with npm version `3.10.10`, node version `6.11.3` on osx. Close issue.
